### ISSUE TITLE
Assets folder is missing...

### ISSUE THREAD

**Issue by MASTER-OF-ORION** [yunyinghu/CVCT_Vulkan#1]
Hi! So, where is Assets folder?
Of course, AssetManager.cpp line 46:
`if(readonly_mapped_file_open(&file,"assets/assets.cache") == 0)		//loads the file, and puts it in memory`
failed...

**Comment by yunyinghu** [comment]
Hey MoO!

Thanks for reporting this issue! Apparently the gitignore file caused the asset folder to not be committed. I can't test it at the moment, because I currently don't have access to a Windows machine. 

For the project to run, you need to have Vulkan SDK installed. You can get the latest version here:
https://vulkan.lunarg.com/sdk/home#windows

The binaries of the project are directly downloadable here:
https://www.dropbox.com/s/bldesz36wx9rpwl/v10_cvct_binary.rar?dl=0

If you don't have the Vulkan SDK installed, you can simply run the Release exe.

**Comment by MASTER-OF-ORION** [comment]
Of course, I already installed Vulkan SDK and your project is going to be launched and started, it just naturally falls with the exception during startup, because can't find assets...
P.S.: Why do you allocate so much virtual memory on the hard drive? I hope the render does not come from HDD :-) ?
